Nathan Anderson-Hobbs

Exercise 1

PUPOL 599 Visual Analytics

```{r}
link='https://github.com/EvansDataScience/VisualAnalytics_2_tabularData/raw/master/data/eduwa.rda'

load(file=url(link))
```



```{r}
library(ggplot2)

tableFreqO=tableFreq[order(tableFreq$pct),]
tableFreqO

base= ggplot(data = tableFreqO, 
             aes(x = locale,
                 y = pct)) 

library(colorspace)

plot1 = base + geom_bar(fill = rainbow_hcl(5, start = 0, end = 200),
                        stat = 'identity') + scale_x_discrete(limits=tableFreqO$locale) 

sourceText = "Source: Unknown"

ytext = "Share of WA public schools"

plot2 = plot1 + labs(title=titleText2,
                     x =NULL, 
                     y = ytext,
                     caption = sourceText)

plot3 = plot2 + geom_hline(yintercept = 25,
                           linetype="dashed", 
                           size=1,
                           alpha=0.3)
library(scales)

plot4 = plot3 + scale_y_continuous(breaks=c(0,10, 25,40,50),
                                 limits = c(0, 50),
                                 labels=scales::unit_format(suffix = '%')) 

plot5 = plot4 + theme(panel.background = element_rect(fill = "white",
                                                    colour = "grey50",
                                                    linetype = 'blank'),
                    axis.line.x.bottom = (element_line(linetype = 'solid')),
                    axis.ticks.y = (element_line(linetype = "blank")),
                    axis.text = (element_text(colour = 'gray25')),
                    axis.title.x = (element_text(colour = 'gray25',
                                                 size = 9,
                                                 margin=unit(c(0.25,0,0,0), 'cm'))),
                    plot.caption = element_text(hjust = 1,
                                                colour = 'gray25',
                                                size = 7),
                    plot.title = element_text(hjust = 0, 
                                              colour = "gray25", 
                                              face = "bold", 
                                              size = 14,
                                              margin=unit(c(0,0,.5,0),"cm")),
                    plot.margin = unit(c(.75,1,0.25,.5),'cm'))
                   
plot6 = plot5 + geom_text(aes(y = pct ,
                            label = paste0(round(pct,2), '%')),
                        hjust=-0.2,
                        size = 2.5)

plot7 = plot6 + coord_flip() 

plot7

```

